version: '3'
services:
  db:
    image: postgres:13.4-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rman
    volumes:
      - local-postgres:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_DB_DRIVER: 'pgsql'
      ADMINER_DEFAULT_DB_HOST: 'db'
      ADMINER_DEFAULT_DB_NAME: 'postgres'

volumes:
  local-postgres:
